/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class JniImpl */

#ifndef _Included_JniImpl
#define _Included_JniImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JniImpl
 * Method:    getCodeAndMask
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_JniImpl_getCodeAndMask
  (JNIEnv *, jclass, jstring);

/*
 * Class:     JniImpl
 * Method:    getIrisFeature
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_JniImpl_getIrisFeature
  (JNIEnv *, jclass, jstring);

/*
 * Class:     JniImpl
 * Method:    matching
 * Signature: (Ljava/lang/String;Ljava/lang/String;)F
 */
JNIEXPORT jfloat JNICALL Java_JniImpl_matching
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     JniImpl
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_JniImpl_sayHello
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
