/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class Demo */

#ifndef _Included_Demo
#define _Included_Demo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Demo
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Demo_sayHello
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
