/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class com_ninn_service_JniImpl */

#ifndef _Included_com_ninn_service_JniImpl
#define _Included_com_ninn_service_JniImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ninn_service_JniImpl
 * Method:    getCodeAndMask
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ninn_service_JniImpl_getCodeAndMask
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_ninn_service_JniImpl
 * Method:    getIrisFeature
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ninn_service_JniImpl_getIrisFeature
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
