/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class jni_JniInterface */

#ifndef _Included_jni_JniInterface
#define _Included_jni_JniInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jni_JniInterface
 * Method:    irisDetect
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jni_JniInterface_irisDetect
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
